### ISSUE TITLE
Question: My generated gcode does not look good?

### ISSUE THREAD

**Issue by HenneCuppens** [Yoyolick/TextToGcode#1]
Hello,

I'm trying out this amazing script. It does exactly what I want, atleast it's supposed to do. I am very very very new to Gcode so my question might even be plain stupid. But I think I'm doing something wrong but I cant figure out what it is. It might be just me, but it seems like it does the letter "e" wrong?

The command im running:
ttg('testing 123', 10, 0, 'file', 1).toGcode("M02 S500", "M05 S0", "G0", "G1")

Generated file (changed to .txt for upload here):
[output.txt](https://github.com/Yoyolick/TextToGcode/files/5981051/output.txt)

Online viewer of GCode:
![image](https://user-images.githubusercontent.com/19166532/107937136-d0d5bf00-6f83-11eb-87cc-76194f78481c.png)

Is this supposed to be like this? Or is the letter 'e' actually wrong?

Thanks in advance.

**Comment by Yoyolick** [comment]
Hmm 🤔 looking at the path it looks like the e might actually be wrong like you are saying, I’ll take a look and see if I can replicate it and fix it. Thanks for bringing this up 😁

**Comment by Yoyolick** [comment]
thanks for bringing this up, it was an error. I've also gone ahead and optimized the library as well so it should be faster too. Please update to 1.2.0 and all should be as expected. @HenneCuppens 

![Screenshot 2021-02-19 201040](https://user-images.githubusercontent.com/43967290/108577382-dcf8ae00-72ee-11eb-8936-fdd62a08b1e5.png)

**Comment by HenneCuppens** [comment]
Amazing, thanks for the effort!

**Comment by Yoyolick** [comment]
I used https://ncviewer.com/ for this, but keep in mind that depending on your off and on commands it will look different. I was using a pen to draw my gcode so my off and on are for moving the pen up and down, if it's for a laser the preview of the gcode will most likely look different.

**Comment by HenneCuppens** [comment]
Thanks man,

I hate to be this guy... But, I noticed a little inconsistency (which for most people probably doesn't even matter) Only I needed this different.  On the letters A and G there was no starter offset. For every other letter it will be set to x0 and y0 or to the correct offset position. But those letters don't, its not a huge deal, do not have this. Since I need to build my own decoder its much easier to have the first setup in a predictable pattern. Now I do not ask you to fix it, I just added (0 + xOff, 0), in the beginning of those letters and its working like I want it to. And I cant see any drawbacks from this? Maybe I missed something.

I just wanted to give you that heads up about this, maybe you want to do something with it, maybe you don't. Either way, thanks a lot for helping me out, making this script and fixing a issue this quick.

**Comment by Yoyolick** [comment]
To me that sounds like it might be a different problem, G does not start at 0,0 but A starts drawing at 0,0. And also I'm not too sure what you mean, you need it to move to 0,0 before drawing? For G it should just move right to the inside of the G and start from there. If you could send some more information I would be glad to take a look at fixing it 😁![image](https://user-images.githubusercontent.com/43967290/108844680-70113c80-75aa-11eb-816b-29d04bade6ef.jpeg)![image](https://user-images.githubusercontent.com/43967290/108844693-730c2d00-75aa-11eb-9634-bf2bb659fa57.jpeg)

**Comment by HenneCuppens** [comment]
Well it was mostly about the first setup. It starts the program on line 5 with G90 (but no coordinates behind them, they come the next line), but for every letter/number except for the A and G the next values (on the next line) gave default X and Y to move to to start the letter. Now I need to build my decoder, and it's much easier if the main drawing starts on the same line every time (otherwise the switch case/if statements can get a real mess).

Im talking about this line:
![image](https://user-images.githubusercontent.com/19166532/109008572-c74c0580-76ad-11eb-8d56-54b99f3f3f5a.png)

**Comment by Yoyolick** [comment]
Thanks for getting back to me, The lines you are talking about with no X or Y commands are used to initialize and tell the cnc information about the job. 

Here they are explained in the code:

![image](https://user-images.githubusercontent.com/43967290/109068153-793efe00-76bd-11eb-854a-023b5fb191ab.png)

This is my output when running:

**from ttgLib.TextToGcode import ttg

print(
    ttg(
        "a b c d e f g h i j k l m n o p q r s t u v w x y z 1 2 3 4 5 6 7 8 9 0",
        1,
        0,
        "file",
        1000,
    ).toGcode("G0Z0", "G0Z20", "G0", "G1")
)**

![sdfsdfdsf](https://user-images.githubusercontent.com/43967290/109068951-8a3c3f00-76be-11eb-9f6e-efe60207b9fb.png)

If you were instead referring to the gcode not saying "go to 0,0" at the very beginning on every letter, that is because the gcode assumes that when it is run, the toolheads initial position in 0,0. Everything else that comes after is offset from that position. If you are talking about adding an x or y offset to the beginning I could probably implement something like that if it would be helpful for you. My main goal with this library is for it to be useful to other people in their projects. Please let me know if this helped 😄

**Comment by HenneCuppens** [comment]
First of, sorry for my late response.

But in your code de G0Z0 command is the first command after the G90. Now I noticed when you start with the letter b in your input. there is gonna be a x/y coördinate inbetween the G90 and G0Z0. This only does not occur with the A and G, then the row is empty. 

I noticed later that maybe the Idea was that the X\Y might have supposed to go behind the G90 instead of below it?

That is what I was trying to say.

**Comment by Yoyolick** [comment]
no worries, I think I understand what you mean now. I think for your decoder you are just going to have to change the code a little bit or find a different way to detect letters (like the on and off commands). There isn't a whole lot I can do about this because it relates to how the letters are drawn. B is already touching (0,0) so it can start drawing right away, but G is not touching (0,0) so it has to move to (5,8) before it starts drawing. Let me know if there is anything else I can help you with!
