### ISSUE TITLE
Letters A and G don't start with a move

### ISSUE THREAD

**Issue by badVibes--** [Yoyolick/TextToGcode#2]
Hello,
I'm trying to use this with my robot and I noticed letters a and g are missing a move command at the start. 
When looking at the code all other characters start with (0 + xOff, 0) or something similar before turning on the tool except these two letters.
Is there any reason for omitting it or is it a bug?

**Comment by Yoyolick** [comment]
Thanks for bringing this up! As far as I can tell this is just an oversight on my part, I'm going to take a closer look at it just to make sure

**Comment by Yoyolick** [comment]
Alright, so I just released 1.3 which added command line usage as well as fixed this issue. I previewed some generated gcode and it appeared that the tool head was not turning off during a move due to the lack of a (0 + xOff, 0) on A, which I added. But in the case of G, it should be ok without it since G doesn't start at 0,0 it starts at different coordinates. 

Let me know if there are any issues with the new release and if this addressed your concerns 😄
